[package]
name = "ttv"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = { git = "https://github.com/kuviman/geng" }
twitch-irc = { version = "4", features = ["with-serde"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
serde = "1"
websocket-lite = "0.5"
reqwest = "0.11"